SystemOrganization addCategory: #'Material-Design-Lite-Demo'!
SystemOrganization addCategory: 'Material-Design-Lite-Demo-Components'!
SystemOrganization addCategory: 'Material-Design-Lite-Demo-Core'!
SystemOrganization addCategory: 'Material-Design-Lite-Demo-Extensions'!
SystemOrganization addCategory: 'Material-Design-Lite-Demo-Utils'!
SystemOrganization addCategory: 'Material-Design-Lite-Demo-Widgets'!
SystemOrganization addCategory: #'Material-Design-Lite-Demo-Widgets'!
