uploaded
MDLWidgetsDemoCssContent
	^ '
.screen-content { 
	margin: 32px;
}	

.mdl-widget-demo-card { 
	margin: auto;
}

.mdl-widget-demo-card .mdl-card__title, .mdl-widget-demo-calendar .mdl-card__title, .mdl-widget-demo-calendar button.active { 
	background-color: rgb(63, 81, 181);
	color: white;	
}

.mdl-widget-demo-calendar button { 
	font-size: 14px;
}

.mdl-widget-demo-calendar button.disabled { 
	color: rgba(0, 0, 0, 0.4);
}	
'