language: smalltalk
sudo: false

os:
- linux
#- osx

smalltalk:
  - Pharo-7.0
  - Pharo-6.1
#- GemStone-3.4.1
  
matrix:
  fast_finish: true
  
# This make Gemstone builds 3x faster
#cache:
#  directories:
#    - $SMALLTALK_CI_CACHE