language: smalltalk
sudo: false

os:
- linux
#- osx

smalltalk:
  - Pharo64-9.0
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo64-6.1
#- GemStone-3.4.1
  
matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo64-9.0
  
# This make Gemstone builds 3x faster
#cache:
#  directories:
#    - $SMALLTALK_CI_CACHE
