rendering
renderPageDescriptionOn: html
	html paragraph: 'The second part of Material Design Lite for Seaside is the Widgets. Widgets are Seaside components with behaviour at the difference of MDL components. They respect Material Design rules and provide to the developers predefined behaviour.'.
	html paragraph: 'An exemple of widget is the nested list already containing features such as dynamic loading of elements, research, sorting...'