Extension { #name : #WAObject }

{ #category : #'*material-design-lite-gemstone' }
WAObject >> rootDialogCloseId [
  "I am the id of the root dialog."

  ^ MDLDialog rootDialogCloseId
]

{ #category : #'*material-design-lite-gemstone' }
WAObject >> rootDialogId [
  "I am the id of the root dialog."

  ^ MDLDialog rootDialogId
]

{ #category : #'*material-design-lite-gemstone' }
WAObject >> rootDialogOpenId [
  "I am the Id to put on a button in order to open the root dialog."

  ^ MDLDialog rootDialogOpenId
]
