font - roboto
robotoCss
	^ '/* cyrillic-ext */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'sTdaA6j0Psb920VjvmrzHkf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
}
/* cyrillic */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'uYECMKoHcO9x1wdmbyHIm3kf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'tnj4SB6DNbdaQnsM8CFqBXkf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'VYFxs824kXqUl2BHqYHkf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'NJ4vxlgWwWbEsv18dAhqnnkf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'KscVxiCiwUWVsFWFA3Bjnkf6ByYO6CLYdB4HQEYWoff2') asString , ') format(''woff2'');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: ''Roboto'';
  font-style: normal;
  font-weight: 400;
  src: local(''Roboto''), local(''Roboto-Regular''), url(' , (self urlOf: 'oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0AWoff2') asString , ') format(''woff2'');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
'