SystemOrganization addCategory: #'Material-Design-Lite-Components'!
SystemOrganization addCategory: 'Material-Design-Lite-Components-Buttons'!
SystemOrganization addCategory: 'Material-Design-Lite-Components-Cards'!
SystemOrganization addCategory: 'Material-Design-Lite-Components-Footer'!
SystemOrganization addCategory: 'Material-Design-Lite-Components-Layout'!
SystemOrganization addCategory: 'Material-Design-Lite-Components-Nav'!
