updating
style
	^ '
 .mdl-card {
    width: 256px;
    height: 256px;
    background: #3E4EB8;
  }

 .mdl-card__actions {
    border-color: rgba(255, 255, 255, 0.2);
  }

 .mdl-card__title,.mdl-card__actions > .mdl-button {
    color: #fff;
  }

 .mdl-snackbar { 
	 z-index: 99999999;
 }
 body {
  	 padding: 20px;
  	 background: #fafafa;
  	 position: relative;
 }

 th a {
	font-family: ''Roboto'', sans-serif;
	color: rgb(138,138,138);
   font-size: 12px;
   text-decoration: none;
 }

 td a { 
	font-family: ''Roboto'', sans-serif;
	color: rgb(222,222,222);
   font-size: 13px;
 }
'