updating
style
	^ '
 .mdl-card {
    background: #3E4EB8;
	 width: 500px;
	 min-height: 300px;
  }

 .mdl-card__actions {
    border-color: rgba(255, 255, 255, 0.2);
  }

 .mdl-card__title,.mdl-card__actions > .mdl-button {
    color: #fff;
  }


 .Calendar { 
	width: 25%;
	text-align: center;
	background-color: ', MDLColor gray lighter lighter lighter lighter lighter asHTMLColor , '; 
 }

 .Calendar > .mdl-grid { 
	padding: 0px;
	width: 90%;
	margin: 5%;
 }

 table { 
	padding-top: 15px;
	width: 90%;
	margin: 5%;
 }

 .number { 
	font-size: 16px;
 }
'

