SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Abstract'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Badge'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Buttons'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Card'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Chips'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Core'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Dialog'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Footer'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Forms'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Layouts'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-List'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Manifest'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-Nav'!
SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-loading'!

SystemOrganization addCategory: #'Material-Design-Lite-Components-Tests-loading'!
