Extension { #name : #MDLLibrary }

{ #category : #'*Material-Design-Lite-Dev-Tools' }
MDLLibrary class >> deployFiles [
	<script>
	super deployFiles
]

{ #category : #'*Material-Design-Lite-Dev-Tools' }
MDLLibrary class >> filesDirectory [
	^ MDLBridge resources
]

{ #category : #'*Material-Design-Lite-Dev-Tools' }
MDLLibrary class >> importFiles [
	<script>
	super importFiles
]

{ #category : #'*Material-Design-Lite-Dev-Tools' }
MDLLibrary class >> openImportButton [
	<script>
	super openImportButton
]
