SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Calendar'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-List'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Poll'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Tab'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Table'!
'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Tab'!
SystemOrganization addCategory: #'Material-Design-Lite-Widgets-Tests-Table'!
