SystemOrganization addCategory: #'Material-Design-Lite-Widgets'!
SystemOrganization addCategory: 'Material-Design-Lite-Widgets-Calendar'!
SystemOrganization addCategory: 'Material-Design-Lite-Widgets-Cards'!
SystemOrganization addCategory: 'Material-Design-Lite-Widgets-Header'!
SystemOrganization addCategory: 'Material-Design-Lite-Widgets-Table'!
SystemOrganization addCategory: 'Material-Design-Lite-Widgets-Tests'!
