"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestMaterialDesignLiteWidgetsTests,
	#superclass : #PackageManifest,
	#category : 'Material-Design-Lite-Widgets-Tests-Manifest'
}

{ #category : #'code-critics' }
ManifestMaterialDesignLiteWidgetsTests class >> ruleRBMissingTranslationsInMenusRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#MDLDialogWidgetTests #testTitle #false)) #'2018-07-10T12:50:37.968201+02:00') )
]
