"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestMaterialDesignLiteComponents,
	#superclass : #PackageManifest,
	#category : 'Material-Design-Lite-Components-Manifest'
}

{ #category : #'meta-data' }
ManifestMaterialDesignLiteComponents class >> description [ ^ 'Material Design Lite for Seaside (MDL) is a library of components for web developers based on Google''s Material Design Philosophy: "A visual language for our users that synthesizes the classic principles of good design with the innovation and possibility of technology and science." Understanding the goals and principles of Material Design is critical to the proper use of the Material Design Lite components. If you have not yet read the Material Design Introduction you should do so before attempting to use the components. (See https://material.io/guidelines/material-design/)

Github: https://github.com/DuneSt/MaterialDesignLite

Demo: https://mdl.ferlicot.fr/

The first part of Material Design Lite for Seaside is the components. The MDL components are created with CSS, JavaScript, and HTML. You can use the components to construct web pages and web apps that are attractive, consistent, and functional. Pages developed with MDL will adhere to modern web design principles like browser portability, device independence, and graceful degradation. Most of them are based on Google''s MDL implementation and provides a binding for Seaside.

The components are made available in the form of Seaside''s brushes.'
]
