"
Description
--------------------

The <div> tag defines a division/section in a document.

Use the <div> tag to group block-elements to format them with styles.
"
Class {
	#name : 'MDLDivTag',
	#superclass : 'WATagBrush',
	#category : 'Material-Design-Lite-Components-Core',
	#package : 'Material-Design-Lite-Components',
	#tag : 'Core'
}

{ #category : 'accessing' }
MDLDivTag >> tag [
	^ 'div'
]
